# -*- coding: utf-8 -*-
"""Лабораторная №3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-n2hUkW_eVa6EuVY10oye62MX1dTzgFQ
"""

i = int(input())
if i == 1:
  print('Январь')
elif i == 2:
  print('Февраль')
elif i == 3:
  print('Март')
elif i == 4:
  print('Апрель')
elif i == 5:
  print('Май')
elif i == 6:
  print('Июнь')
elif i == 7:
  print('Июль')
elif i == 8:
  print('Август')
elif i == 9:
  print('Сентябрь')
elif i == 10:
  print('Октябрь')
elif i ==11:
  print('Ноябрь')
elif i == 12:
  print('Декабрь')
else:
  print('Такого месяца нет')

i = int(input())
if i%2==0:
  print('Четное')
else:
  print('Нечетное')

i = int(input())
if i > 40:
  print('stonks')
else:
  print('not stonks')

is_year_leap = int(input())
if is_year_leap % 4 == 0:
  print('True')
else:
  print('False')

n = int(input())
c = 0
for s in range(1, n+1):
  if n%s == 0:
    c = c + 1
if c == 2:
  print('True')
else:
  print('False')

a = float(input())
b = float(input())
if a//3.6==b:
  ta = a
  tb = b
  a = tb
  b = ta
elif b > ((-138/2)**1.3) and b < (-69/(28**5.1)*4):
  ta = a
  tb = b
  a = tb
  b = ta
print(a, b)